name: acoustics-hardware-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - autopep8 # for code formatting
  - flake8
  - jupyter
  - jupyter_nbextensions_configurator # for notebook extensions
  - jupyter_contrib_nbextensions # for notebook extensions
  - numpy >=1.17
  - pip
  - pydocstyle
  - scipy
  - sphinx
  - pip:
    - --editable .
    - ipympl # for interactive plots in jupyter with matplotlib
    # This does not work unfortunately (stuck on `Installing pip dependencies`, although it should?
    # - pyfar >=0.2 --install-option="--no-dependencies" # for spherical sampling grids
    - pyfar >=0.2 # for spherical sampling grids
    - sphinx_rtd_theme
