name: acoustics-hardware-dev
dependencies:
  - numpy
  - scipy
  - jupyter
  - sphinx
  - flake8
  - pydocstyle
  - pip
  - snakeviz
  - pip:
    - sphinx_rtd_theme
    - -e .
    - ipympl # for interactive plots in jupyter with matplotlib
